import Foundation

// MARK: - Usage Information Types

/// Token usage and billing information for AI operations.
///
/// The `Usage` types provide detailed information about token consumption,
/// which is essential for billing, monitoring, and optimization of AI operations.
/// These types follow the standard patterns established by major AI providers.

// MARK: - Usage

/// Token usage information for a single AI operation.
///
/// `Usage` tracks the token consumption for both input (prompt) and output
/// (completion) portions of an AI operation. This information is crucial for
/// understanding costs and optimizing token usage.
///
/// ## Token Types
/// - **Input Tokens**: Tokens from the prompt, conversation history, and system messages
/// - **Output Tokens**: Tokens generated by the model in the response
/// - **Total Tokens**: Sum of input and output tokens
///
/// ## Usage Examples
///
/// ### Basic Usage Creation
/// ```swift
/// let usage = Usage(
///     promptTokens: 25,
///     completionTokens: 100,
///     totalTokens: 125
/// )
/// ```
///
/// ### With Additional Information
/// ```swift
/// let usage = Usage(
///     promptTokens: 50,
///     completionTokens: 200,
///     totalTokens: 250,
///     promptCost: 0.001,
///     completionCost: 0.002,
///     totalCost: 0.003
/// )
/// ```
public struct Usage: Sendable {
    
    // MARK: - Token Counts
    
    /// Number of tokens in the input (prompt, conversation history, system message).
    ///
    /// This includes all tokens that were sent to the model as context,
    /// including the user's prompt, conversation history, system instructions,
    /// and any tool definitions.
    public let promptTokens: Int
    
    /// Number of tokens generated by the model in the response.
    ///
    /// This includes the text content, tool calls, and any other content
    /// generated by the model. Also known as "completion tokens" or "output tokens".
    public let completionTokens: Int
    
    /// Total number of tokens (promptTokens + completionTokens).
    ///
    /// This is the sum of input and output tokens and represents the total
    /// token consumption for this operation.
    public let totalTokens: Int
    
    // MARK: - Cost Information (Optional)
    
    /// Cost for the prompt tokens in the provider's currency.
    ///
    /// When available, this provides the actual cost for the input portion
    /// of the request based on the provider's pricing model.
    public let promptCost: Double?
    
    /// Cost for the completion tokens in the provider's currency.
    ///
    /// When available, this provides the actual cost for the output portion
    /// of the request based on the provider's pricing model.
    public let completionCost: Double?
    
    /// Total cost for this operation in the provider's currency.
    ///
    /// When available, this should equal promptCost + completionCost.
    public let totalCost: Double?
    
    /// Currency used for cost calculations (e.g., "USD", "EUR").
    ///
    /// Indicates the currency for the cost fields. Defaults to "USD" if not specified.
    public let currency: String?
    
    // MARK: - Additional Information
    
    /// Additional usage details that may be provider-specific.
    ///
    /// Some providers may include additional usage information such as:
    /// - Cache hit rates
    /// - Processing time
    /// - Model-specific metrics
    /// - Detailed breakdowns by message type
    public let details: [String: String]?
    
    // MARK: - Initialization
    
    /// Creates a new Usage instance with the specified token counts and optional cost information.
    ///
    /// - Parameters:
    ///   - promptTokens: Number of input tokens
    ///   - completionTokens: Number of output tokens
    ///   - totalTokens: Total tokens (should equal promptTokens + completionTokens)
    ///   - promptCost: Optional cost for input tokens
    ///   - completionCost: Optional cost for output tokens
    ///   - totalCost: Optional total cost
    ///   - currency: Currency for cost values (defaults to "USD")
    ///   - details: Optional additional usage details
    public init(
        promptTokens: Int,
        completionTokens: Int,
        totalTokens: Int,
        promptCost: Double? = nil,
        completionCost: Double? = nil,
        totalCost: Double? = nil,
        currency: String? = nil,
        details: [String: String]? = nil
    ) {
        self.promptTokens = promptTokens
        self.completionTokens = completionTokens
        self.totalTokens = totalTokens
        self.promptCost = promptCost
        self.completionCost = completionCost
        self.totalCost = totalCost
        self.currency = currency
        self.details = details
    }
    
    /// Convenience initializer that automatically calculates total tokens.
    ///
    /// - Parameters:
    ///   - promptTokens: Number of input tokens
    ///   - completionTokens: Number of output tokens
    ///   - promptCost: Optional cost for input tokens
    ///   - completionCost: Optional cost for output tokens
    ///   - currency: Currency for cost values
    ///   - details: Optional additional usage details
    public init(
        promptTokens: Int,
        completionTokens: Int,
        promptCost: Double? = nil,
        completionCost: Double? = nil,
        currency: String? = nil,
        details: [String: String]? = nil
    ) {
        self.init(
            promptTokens: promptTokens,
            completionTokens: completionTokens,
            totalTokens: promptTokens + completionTokens,
            promptCost: promptCost,
            completionCost: completionCost,
            totalCost: (promptCost ?? 0) + (completionCost ?? 0),
            currency: currency,
            details: details
        )
    }
}

// MARK: - Usage Extensions

public extension Usage {
    
    /// Calculate the ratio of completion tokens to total tokens.
    ///
    /// This can be useful for understanding how much of the token usage
    /// was for the generated content versus the input context.
    ///
    /// - Returns: Ratio between 0.0 and 1.0, or 0.0 if total tokens is 0
    var completionRatio: Double {
        guard totalTokens > 0 else { return 0.0 }
        return Double(completionTokens) / Double(totalTokens)
    }
    
    /// Calculate the ratio of prompt tokens to total tokens.
    ///
    /// This can be useful for understanding how much of the token usage
    /// was for the input context versus the generated content.
    ///
    /// - Returns: Ratio between 0.0 and 1.0, or 0.0 if total tokens is 0
    var promptRatio: Double {
        guard totalTokens > 0 else { return 0.0 }
        return Double(promptTokens) / Double(totalTokens)
    }
    
    /// Check if this usage information includes cost data.
    var hasCostInformation: Bool {
        return promptCost != nil || completionCost != nil || totalCost != nil
    }
    
    /// Estimated words in the completion (rough approximation).
    ///
    /// This provides a rough estimate of the number of words in the generated
    /// content based on the common approximation of 1 token ≈ 0.75 words for English.
    var estimatedCompletionWords: Int {
        return Int(Double(completionTokens) * 0.75)
    }
    
    /// Estimated words in the prompt (rough approximation).
    ///
    /// This provides a rough estimate of the number of words in the input
    /// content based on the common approximation of 1 token ≈ 0.75 words for English.
    var estimatedPromptWords: Int {
        return Int(Double(promptTokens) * 0.75)
    }
    
    /// Create a usage summary string for logging or display.
    ///
    /// - Returns: A human-readable summary of the usage information
    var summary: String {
        var components = ["📊 \(totalTokens) tokens (\(promptTokens) in, \(completionTokens) out)"]
        
        if hasCostInformation {
            if let total = totalCost, let currency = currency {
                components.append("💰 \(String(format: "%.4f", total)) \(currency)")
            }
        }
        
        return components.joined(separator: " • ")
    }
}

// MARK: - Usage Arithmetic

public extension Usage {
    
    /// Add two usage instances together.
    ///
    /// This is useful for combining usage across multiple operations
    /// or accumulating usage over time.
    ///
    /// - Parameter other: The other usage to add
    /// - Returns: A new Usage instance with combined values
    func adding(_ other: Usage) -> Usage {
        return Usage(
            promptTokens: self.promptTokens + other.promptTokens,
            completionTokens: self.completionTokens + other.completionTokens,
            totalTokens: self.totalTokens + other.totalTokens,
            promptCost: addOptional(self.promptCost, other.promptCost),
            completionCost: addOptional(self.completionCost, other.completionCost),
            totalCost: addOptional(self.totalCost, other.totalCost),
            currency: self.currency ?? other.currency,
            details: combineDetails(self.details, other.details)
        )
    }
    
    /// Add multiple usage instances together.
    ///
    /// - Parameter usages: Array of usage instances to combine
    /// - Returns: A new Usage instance with combined values
    static func sum(_ usages: [Usage]) -> Usage {
        return usages.reduce(Usage.zero) { $0.adding($1) }
    }
    
    /// Zero usage (no tokens, no cost).
    static let zero = Usage(promptTokens: 0, completionTokens: 0, totalTokens: 0)
    
    // MARK: - Private Helpers
    
    private func addOptional(_ a: Double?, _ b: Double?) -> Double? {
        switch (a, b) {
        case (let a?, let b?): return a + b
        case (let a?, nil): return a
        case (nil, let b?): return b
        case (nil, nil): return nil
        }
    }
    
    private func combineDetails(_ a: [String: String]?, _ b: [String: String]?) -> [String: String]? {
        switch (a, b) {
        case (let a?, let b?): return a.merging(b) { _, new in new }
        case (let a?, nil): return a
        case (nil, let b?): return b
        case (nil, nil): return nil
        }
    }
}

// MARK: - Legacy Type Alias

/// Legacy type alias for backward compatibility.
///
/// `TokenUsage` was the original name for usage information in the SDK.
/// This alias maintains backward compatibility while the new `Usage` name
/// aligns better with industry standards.
public typealias TokenUsage = Usage

// MARK: - Codable Conformance

extension Usage: Codable {
    
    /// Custom encoding to handle the Any dictionary properly
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        try container.encode(promptTokens, forKey: .promptTokens)
        try container.encode(completionTokens, forKey: .completionTokens)
        try container.encode(totalTokens, forKey: .totalTokens)
        try container.encodeIfPresent(promptCost, forKey: .promptCost)
        try container.encodeIfPresent(completionCost, forKey: .completionCost)
        try container.encodeIfPresent(totalCost, forKey: .totalCost)
        try container.encodeIfPresent(currency, forKey: .currency)
        
        // Note: details dictionary is properly encoded as [String: String]
        // Providers should include specific details in their own response types
    }
    
    /// Custom decoding that ignores the details field
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        promptTokens = try container.decode(Int.self, forKey: .promptTokens)
        completionTokens = try container.decode(Int.self, forKey: .completionTokens)
        totalTokens = try container.decode(Int.self, forKey: .totalTokens)
        promptCost = try container.decodeIfPresent(Double.self, forKey: .promptCost)
        completionCost = try container.decodeIfPresent(Double.self, forKey: .completionCost)
        totalCost = try container.decodeIfPresent(Double.self, forKey: .totalCost)
        currency = try container.decodeIfPresent(String.self, forKey: .currency)
        
        // details is not decoded and remains nil
        details = nil
    }
    
    private enum CodingKeys: String, CodingKey {
        case promptTokens = "prompt_tokens"
        case completionTokens = "completion_tokens"
        case totalTokens = "total_tokens"
        case promptCost = "prompt_cost"
        case completionCost = "completion_cost"
        case totalCost = "total_cost"
        case currency
    }
}

// MARK: - Equatable Conformance

extension Usage: Equatable {
    
    /// Compare two Usage instances for equality.
    ///
    /// Note: The details dictionary is compared properly since it contains [String: String]
    /// which is not Equatable. Only the token counts and cost information are compared.
    public static func == (lhs: Usage, rhs: Usage) -> Bool {
        return lhs.promptTokens == rhs.promptTokens &&
               lhs.completionTokens == rhs.completionTokens &&
               lhs.totalTokens == rhs.totalTokens &&
               lhs.promptCost == rhs.promptCost &&
               lhs.completionCost == rhs.completionCost &&
               lhs.totalCost == rhs.totalCost &&
               lhs.currency == rhs.currency
    }
}

// MARK: - Hashable Conformance

extension Usage: Hashable {
    
    /// Hash this Usage instance.
    ///
    /// Note: The details dictionary is not included in the hash since it contains
    /// [String: String] which is Hashable.
    public func hash(into hasher: inout Hasher) {
        hasher.combine(promptTokens)
        hasher.combine(completionTokens)
        hasher.combine(totalTokens)
        hasher.combine(promptCost)
        hasher.combine(completionCost)
        hasher.combine(totalCost)
        hasher.combine(currency)
    }
}